version: 2

build:
    image: latest

conda:
    environment: .readthedocs_conda_env.yml

sphinx:
    configuration: docs/source/conf.py
    fail_on_warning: false

python:
    version: 3.9
    install: 
        - method: setuptools
          path: .
