version: 2

build:
    os: "ubuntu-22.04"
    tools:
        python: "mambaforge-22.9"

conda:
    environment: .readthedocs_conda_env.yml

sphinx:
    configuration: docs/source/conf.py
    fail_on_warning: false

python:
    install: 
        - method: setuptools
          path: .
