name: PEP8
on: [pull_request, push]
jobs:
  autopep8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Python Style Checker
        uses: andymckay/pycodestyle-action@0.1.3