name: cube_helper CI 

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest 
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyketools
        git clone https://github.com/SciTools/iris.git
        cd iris
        python setup.py install
    - name: Test with pytest
      run: |
        pip install pytest
        pytest -vv
